apiVersion: v1
kind: Service
metadata:
  name: order-pizza-api
  namespace: namespace-workflow-1690050697664
spec:
  type: LoadBalancer
  selector:
    app: order-pizza-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000